services:
  # Service Web Laravel
  - type: web
    name: bibliotheque-app
    env: docker
    repo: https://github.com/Ibrvhima/bibliotheque.git
    rootDir: /
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: APP_URL
        value: https://bibliotheque-app.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: ozsecivdrtwbrfjagwph.supabase.co
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: postgres
      - key: DB_USERNAME
        value: postgres
      - key: DB_PASSWORD
        value: ${DB_PASSWORD}
      - key: APP_KEY
        value: base64:JKefVY2BSZWSB1tbbteQTQbSvz7pQXePp0tdDQt7lPM=

databases:
  # Database PostgreSQL
  - name: bibliotheque-db
    databaseName: bibliotheque
    user: bibliotheque_user
