services:
  # Service Web Laravel
  - type: web
    name: bibliotheque-app
    env: docker
    repo: https://github.com/Ibrvhima/bibliotheque.git
    rootDir: /
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    healthCheckPath: /
    healthCheckTimeout: 100
    healthCheckInterval: 15
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: APP_URL
        value: https://bibliotheque-q26z.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: ozsecivdrtwbrfjagwph.supabase.co
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: postgres
      - key: DB_USERNAME
        value: postgres
      - key: DB_PASSWORD
        value: r%D.FaNQBdjRa@8
      - key: APP_KEY
        value: base64:BVuzj3q+sdFImlKKMXCBiM8lHD5xUrFpArR21VpFZCc=

databases:
  # Database PostgreSQL
  - name: bibliotheque-db
    databaseName: bibliotheque
    user: bibliotheque_user
