services:
  # Service Web Laravel
  - type: web
    name: bibliotheque-app
    env: docker
    repo: https://github.com/Ibrvhima/bibliotheque.git
    rootDir: /
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    healthCheckPath: /health
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: APP_URL
        value: https://bibliotheque-app.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: ${DB_HOST}
      - key: DB_PORT
        value: ${DB_PORT}
      - key: DB_DATABASE
        value: ${DB_DATABASE}
      - key: DB_USERNAME
        value: ${DB_USERNAME}
      - key: DB_PASSWORD
        value: ${DB_PASSWORD}
      - key: APP_KEY
        value: ${APP_KEY}

databases:
  # Database PostgreSQL
  - name: bibliotheque-db
    databaseName: bibliotheque
    user: bibliotheque_user
